// ***** Author *****//

export const AUTHOR_ACTIONS = {
  // CREATE
  CREATE_AUTHOR_REQUEST: 'CREATE_AUTHOR_REQUEST',
  CREATE_AUTHOR_SUCCESS: 'CREATE_AUTHOR_SUCCESS',
  CREATE_AUTHOR_FAILURE: 'CREATE_AUTHOR_FAILURE',
  // GET ALL
  GET_ALL_AUTHOR_REQUEST: 'GET_ALL_AUTHOR_REQUEST',
  GET_ALL_AUTHOR_SUCCESS: 'GET_ALL_AUTHOR_SUCCESS',
  GET_ALL_AUTHOR_FAILURE: 'GET_ALL_AUTHOR_FAILURE',
  // SELECTED_AUTHOR_ID
  SELECTED_AUTHOR_ID: 'SELECTED_AUTHOR_ID',
  // UPDATE
  UPDATE_AUTHOR_REQUEST: 'UPDATE_AUTHOR_REQUEST',
  UPDATE_AUTHOR_SUCCESS: 'UPDATE_AUTHOR_SUCCESS',
  UPDATE_AUTHOR_FAILURE: 'UPDATE_AUTHOR_FAILURE',
  // DELETE
  DELETE_AUTHOR_REQUEST: 'DELETE_AUTHOR_REQUEST',
  DELETE_AUTHOR_SUCCESS: 'DELETE_AUTHOR_SUCCESS',
  DELETE_AUTHOR_FAILURE: 'DELETE_AUTHOR_FAILURE',
};

// ***** Book ***** //

export const BOOK_ACTIONS = {
  //CREATE
  CREATE_BOOK_REQUEST: 'CREATE_BOOK_REQUEST',
  CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
  CREATE_BOOK_FAILURE: 'CREATE_BOOK_FAILURE',
  BOOK_SELECT_ID: 'BOOK_SELECT_ID',
};
