// ***** Author *****

export const AUTHOR_ACTIONS = {
  CREATE_AUTHOR_REQUEST: 'CREATE_AUTHOR_REQUEST',
  CREATE_AUTHOR_SUCCESS: 'CREATE_AUTHOR_SUCCESS',
  CREATE_AUTHOR_FAILURE: 'CREATE_AUTHOR_FAILURE',
};
