// ***** Author *****

export const AUTHOR_ACTIONS = {
  // CREATE
  CREATE_AUTHOR_REQUEST: 'CREATE_AUTHOR_REQUEST',
  CREATE_AUTHOR_SUCCESS: 'CREATE_AUTHOR_SUCCESS',
  CREATE_AUTHOR_FAILURE: 'CREATE_AUTHOR_FAILURE',
  // GET ALL
  GET_ALL_AUTHOR_REQUEST: 'GET_ALL_AUTHOR_REQUEST',
  GET_ALL_AUTHOR_SUCCESS: 'GET_ALL_AUTHOR_SUCCESS',
  GET_ALL_AUTHOR_FAILURE: 'GET_ALL_AUTHOR_FAILURE',
};
